CC = gcc

CFLAGS = -Wall

all: print_args open_file write_file mycp mycat

print_args: print_args.c

open_file: open_file.c

write_file: write_file.c

mycp: mycp.c

mycat: mycat.c

clean:
	rm *.o print_args open_file write_file mycp mycat *.txt