CC = gcc

CFLAGS = -Wall

all: exer1 exer2 exer3 exer4 exer5 exer6 exer7

exer7: exer7.c

exer6: exer6.c

exer5: exer5.c

exer4: exer4.c

exer3: exer3.c

exer2: exer2.c

exer1: exer1.c

clean:
	rm exer1 exer2 exer3 exer4 exer5 exer6 exer7